import type { AnalysisResult } from "@/types/analysis";

/**
 * Generates a plain-text report from the analysis result and triggers
 * a browser download as a .txt file.
 *
 * Args:
 *   result: The full analysis result object.
 */
export function downloadReport(result: AnalysisResult): void {
  const lines: string[] = [
    "═══════════════════════════════════════════",
    "  ATS Resume Match Report",
    "═══════════════════════════════════════════",
    "",
    `Overall Score:  ${result.score}/100`,
    `Verdict:        ${result.verdict}`,
    `Reason:         ${result.verdict_reason}`,
    "",
    "───────────────────────────────────────────",
    "  Dimension Scores",
    "───────────────────────────────────────────",
    `  Skills:          ${result.skill_score}/100`,
    `  Experience:      ${result.experience_score}/100`,
    `  Education:       ${result.education_score}/100`,
    `  Keywords:        ${result.keyword_density_score}/100`,
    `  Impact:          ${result.impact_score}/100`,
    `  Tailoring:       ${result.tailoring_score}/100`,
    `  Title Alignment: ${result.title_alignment_score}/100`,
    "",
    "───────────────────────────────────────────",
    `  Keywords Matched (${result.keywords_matched.length})`,
    "───────────────────────────────────────────",
    result.keywords_matched.length
      ? result.keywords_matched.map((k) => `  ✓ ${k}`).join("\n")
      : "  (none)",
    "",
    "───────────────────────────────────────────",
    `  Keywords Missing (${result.keywords_missing.length})`,
    "───────────────────────────────────────────",
    result.keywords_missing.length
      ? result.keywords_missing.map((k) => `  ✗ ${k}`).join("\n")
      : "  (none)",
    "",
  ];

  if (result.red_flags.length) {
    lines.push(
      "───────────────────────────────────────────",
      "  Red Flags",
      "───────────────────────────────────────────",
    );
    for (const flag of result.red_flags) {
      lines.push(`  [${flag.type.toUpperCase()}] ${flag.label}`);
      lines.push(`    ${flag.detail}`);
    }
    lines.push("");
  }

  if (result.strong_points.length) {
    lines.push(
      "───────────────────────────────────────────",
      "  Strong Points",
      "───────────────────────────────────────────",
    );
    for (const pt of result.strong_points) {
      lines.push(`  ✓ ${pt}`);
    }
    lines.push("");
  }

  if (result.tips.length) {
    lines.push(
      "───────────────────────────────────────────",
      "  Recommendations",
      "───────────────────────────────────────────",
    );
    for (const tip of result.tips) {
      const icon = tip.type === "ok" ? "✓" : tip.type === "warn" ? "!" : "i";
      lines.push(`  [${icon}] ${tip.text}`);
    }
    lines.push("");
  }

  if (result.skills_gap.length) {
    lines.push(
      "───────────────────────────────────────────",
      "  Skills to Add",
      "───────────────────────────────────────────",
    );
    lines.push(`  ${result.skills_gap.join(", ")}`);
    lines.push("");
  }

  lines.push(
    "───────────────────────────────────────────",
    `  Generated by ATS Matcher · ${new Date().toLocaleDateString()}`,
    "───────────────────────────────────────────",
  );

  const text = lines.join("\n");
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `ats-report-${result.score}-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
